---
- hosts: localhost
  connection: local
  become: yes

  tasks:
  - name: Create tempdir
    ansible.builtin.tempfile:
      state: directory
    register: tempdir

  - name: Download whoami tarball
    ansible.builtin.get_url:
      url: https://github.com/traefik/whoami/releases/download/v1.11.0/whoami_v1.11.0_linux_amd64.tar.gz
      dest: "{{ tempdir.path }}/whoami.tar.gz"

  - name: Set tempdir permissions
    ansible.builtin.file:
      path: "{{ tempdir.path }}"
      mode: "0755"

  - name: Extract whoami tarball
    ansible.builtin.unarchive:
      src: "{{ tempdir.path }}/whoami.tar.gz"
      dest: "{{ tempdir.path }}"
      include: 
      - whoami
  
  - name: Install binary
    ansible.builtin.copy:
      src: "{{ tempdir.path }}/whoami"
      dest: /usr/local/bin/traefik-whoami
      mode: "0755"

  - name: Add whoami user
    ansible.builtin.user:
      name: whoami
      comment: Traefik whoami service user
      system: true

  - name: Add Supervisor config
    ansible.builtin.copy:
      src: whoami.conf
      dest: /etc/supervisor/conf.d/whoami.conf
